### ISSUE TITLE
Allow multi-service definition via YAML

### ISSUE THREAD

**Issue by RohitKochhar** [RohitKochhar/talbot#21]
Add functionality that would allow multiple microservices to be defined from a single YAML.  For example, a YAML file like:

```yaml
serverName: project_name
parentDirectory: ./project
microservices:
  - appName: microservice-1
     childDirectory: microservice_1
     endpoints:
       - path: /v1/healthcheck
          method: GET
          desc: "Something"
   - appName: microservice-2
      childDirectory: microservice_2
      endpoints:
       - path: /v1/healthcheck
          method: GET
          desc: "Something"
```

Should create two microservices in paths of `./project/microservice_1` and `./project/microservice_2`, and the `docker-compose.yaml` should be located at the top-level of `project` and include the images built from the Dockerfiles in the microservice directories.
