### ISSUE TITLE
Allow additional YAML configuration

### ISSUE THREAD

**Issue by RohitKochhar** [RohitKochhar/talbot#3]
To allow for more flexible scaffolding, users should be able to provide a YAML file containing certain configuration settings for their scaffolding app. If a YAML file is provided, no other flags should be needed, that is, the YAML should be able to provide all the information previously accepted by the flags

The YAML file should be accepted by the program like:

```
talbot make -c conf.yaml
```

The YAML could look something like this:

```yaml
name: app_name
mod_name: module_name
directory: relative directory
endpoints:
  - path: /v1/healthcheck
     method: GET
     description: "some description"
  - path: /v1/upload
     method: PUT
     description: "some description"
```

The program should then configure the app like normal, template the router to connect the endpoints to their specific handler functions and update the README to contain the information on the endpoints
